### ISSUE TITLE
Changes in List view structure

### ISSUE THREAD

**Issue by lukaszjaroszynski** [lukaszjaroszynski/Gepado-at-LifeLabs#6]
There is a need to reconfigure the list view of a number of fields (remove and add some, also rename some of them, e.g remove BRCA number from person list view). Explanation how to perform this is necessary.

This is the determined in the table config list2. 
The table config list2. can be  manage and elongate with additional fields from detail view. To be shown during the Telco with LL on April 22nd

**Comment by lbirchall** [comment]
We are having an issue with replicating what was shown to us in the last Telco/WebEx meeting. When we look at the dbo.t_config_list2 table in the SQL database there does not appear to be an entry for brca number that we can make not visible or for fremid or id_vm to make visible. Further clarification is required.

**Comment by lukaszjaroszynski** [comment]
moved to BSCgepado/CA-LL-LifeLabs  Folder, here case is closed
